### ISSUE TITLE
Taoup runs slow

### ISSUE THREAD

**Issue by ronjouch** [globalcitizen/taoup#11]
I like to run taoup at shell startup.

But after a pass of cleanup/optimization, I ended up removing it, after noticing it takes a big chunk of my shell's startup time:

```bash
[ronj@t ~]$ time taoup-fortune
< Law of Communications: The inevitable result of improved and enlarged communications between different levels in a hierarchy is a vastly increased area of misunderstanding. >

real    0m0,305s
user    0m0,237s
sys     0m0,119s
```

For me on a recent laptop with ruby 2.6.3p62, it takes between 0.2 and 0.4s, which is a noticeable delay, especially given the small task it accomplishes.

1. Does the number match your experience?
2. Any suggestions to speed this up with the current Ruby implementation? (I know Python is quite fast to boot, but I don't know Ruby at all, is its boot time a big part of taoup's execution time?)
3. Would a pure POSIX shell rewrite make sense?

Anyway, thanks for the collection and frequent additions 🙂.

---

**EDIT** workaround: why always calling ruby at each call when you can simply dumping the fortunes to a static cache and shuffle that:

After git clone,
```bash
./taoup | grep -v '^---' > taoup.txt
```

Then `taoup-fortune` can be as simple as a call to unix `shuf`:
```bash
#!/usr/bin/env sh
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
shuf -n 1 "$dir/taoup.txt"
```

**Comment by globalcitizen** [comment]
Yes, it's not fast. However, it's not a problem for me. Your approach is a good one. If you would like to contribute an optimized portable shell script with this approach and create a pull request I can assign you credit in the git history.

**Comment by globalcitizen** [comment]
@ronjouch OK here's an idea. The existing `taoup-fortune` script runs `md5sum` or `md5` (as available; the latter being normal on OSX) on the `taoup` file. A filename is generated, `.taoup.cache.<hash>`. If the file does not exist, it is generated by storing the output of `taoup`. The file is then read as if it is the output of the program.

**Comment by ronjouch** [comment]
> @ronjouch OK here's an idea. The existing `taoup-fortune` script runs `md5sum` or `md5` (as available; the latter being normal on OSX) on the `taoup` file. A filename is generated, `.taoup.cache.<hash>`. If the file does not exist, it is generated by storing the output of `taoup`. The file is then read as if it is the output of the program.

@globalcitizen that would work, but I already have tooling around updating git repos (such as taoup) and post-actions, so for my current "on-the-side" solution is even better for me, as it happens only once every repo update. Here's what it looks like:

```bash
# update taoup to latest master. post-update:cache it
git-update master 'https://github.com/globalcitizen/taoup.git' /opt/taoup "./taoup | grep -v '^---' > taoup.txt"
```

One nit regarding your solution: one file per hash would lead to polluting the folder with tons of `.taoup.cache.<hash>` files. It seems more reasonable to output hash to a file (`.taoup.cache`), and contents to another file (`taoup.md5sum`). Then the script can compare md5 to `cat .taoup.md5sum`, and overwrite `.taoup.cache` if necessary.

**Comment by globalcitizen** [comment]
Implemented. You can `rm .taoup-fortune.*` in your script after updating to get automatic cache regeneration.

**Comment by globalcitizen** [comment]
Added `shuf`.

**Comment by ronjouch** [comment]
@globalcitizen cool! Thanks for listening! 🙂
