### ISSUE TITLE
requires gem install

### ISSUE THREAD

**Issue by BardiaAfshin** [globalcitizen/taoup#2]
gem install ansi

You can puts this in a bundle file or have the taoup check for it's existence and install it

```ruby
begin
  gem "ansi"
rescue Gem::LoadError
  `gem install ansi`
end
```

**Comment by globalcitizen** [comment]
True enough, that's possible. However, we don't actually know whether `gem` is installed, where the user wants to install gems (system or user level installation is possible), what their current permissions are ... and anyway, running random things on the user's system without their explicit permission is bad form.
