### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by zakame** [globalcitizen/taoup#21]
Hi, thanks for this excellent piece of software! :tada: 

I just want to ask for clarification WRT GPL3 licensing - is this going to use GPL3 _only_, or GPL3 _or any later version_?  I ask because I'm packaging this for Nix, see https://github.com/NixOS/nixpkgs/pull/136751, and even when checking the `taoup` script itself I didn't find the recommended [notice](https://github.com/globalcitizen/taoup/blob/83d355ddac16f43ce075a34933f3a76ce027011b/LICENSE#L623-L674) to guide me to knowing under what GPL3 license this software is under.

Thanks in advance!

**Comment by globalcitizen** [comment]
Cheers @zakame ! Love Nix! Also love packagers! I will add a `LICENSE` file and set contents to report "GPL3 or or later version", then do a new release so it's a clean start for you. Will report back shortly.

**Comment by globalcitizen** [comment]
OK just checked and there is a `LICENSE` file already. It says GPLv3 (only). Not mucking with that.

Did a new release for you [v1.1.14](https://github.com/globalcitizen/taoup/releases/tag/v1.1.14).

Thanks for packaging! When it is live, let me know here what the package details are so I can add them to the README for easy installation by Nix users.

**Comment by zakame** [comment]
Thanks @globalcitizen for the new release, I've updated my PR and hope it gets in soon, will definitely let you know! 🤞 🚀

**Comment by zakame** [comment]
Hi @globalcitizen! `taoup` is [now available in Nixpkgs](https://search.nixos.org/packages?channel=unstable&show=taoup&from=0&size=50&sort=relevance&type=packages&query=taoup)!  Thanks again for this software! 🎉

**Comment by globalcitizen** [comment]
Thanks @zakame! Go Nix!
