### ISSUE TITLE
Release numbers mismatch?

### ISSUE THREAD

**Issue by zakame** [globalcitizen/taoup#25]
Hi, thanks again for this great software! 🎉 

I noticed that the latest [Release](https://github.com/globalcitizen/taoup/releases) is about `taoup-1.1.21`, but the versioned tag is [`v1.21`](https://github.com/globalcitizen/taoup/tree/v1.21) - which should be the correct number?  I found this while packaging the update for [Nixpkgs](https://github.com/NixOS/nixpkgs/pull/262330)...

**Comment by globalcitizen** [comment]
Oh thanks, sorry yeah probably a typo. I will be more careful next time. Super busy of late haven't had bandwidth for open source stuff. Thanks for packaging :)

**Comment by globalcitizen** [comment]
My bad!
