### ISSUE TITLE
Add a flag for different colors

### ISSUE THREAD

**Issue by nullp0tr** [globalcitizen/taoup#4]
Can we help out users of non-dark terminals by adding a flag to use different colors? I wanna read but it hurts my eyes to do so:D

**Comment by globalcitizen** [comment]
It's surely possible. But is there much demand? This is the first time anyone has requested it.

I'm not motivated personally but I can see the value.

If you wanted to tackle it, I would suggest implementing via an overwrite function, similar to the ascii-only / fortune mode.

The first step would be looking up the ANSI module's mechanism for color selection. Then, figure out how to overwrite it. Finally, wrap it in a mode-driven setup function. The rest of the code then stays the same.

**Comment by nullp0tr** [comment]
Thanks a lot for the addition, I'm sorry I couldn't help out with it. The flag name you picked is hilarious, and this is coming from what you'd call whitetrash I guess..

**Comment by globalcitizen** [comment]
Cheers, indeed I am also anglo but don't take things seriously!
