### ISSUE TITLE
Fake news: Electrical engineer's motto? Possibly missing: Resistor color codes. 

### ISSUE THREAD

**Issue by polytomous** [globalcitizen/taoup#5]
So I was doing some research into this particular message, and I have a few concerns: 
https://github.com/globalcitizen/taoup/blob/40f7a6851e0336c4137a0448e0506026ae914afd/taoup#L1307

1. Is this fake news? 

I couldn't find any groups of electrical engineers that advertised this as their motto. From what I understand, this isn't *actually* a motto at all, but just a really mediocre old joke from list servs. 

2. Are we not doing enough? 

Engineering has plenty of inappropriate acronyms and jokes. Should we add resistor color codes as well? I can prepare a pr for that if you like.

3. Is the motto even reasonable? 

Are you supposed to consult your doctor if your computer works for longer than four hours? Asking for a friend.

**Comment by globalcitizen** [comment]
It's one of those sense of humour things.

**Comment by polytomous** [comment]
No, I think it's incorrect advice. Your repo says: 

>"This is a ruby-powered, ANSI-enabled, fortune-like program to espouse wisdom at opportune moments, such as when you log in." 

Erections are fleeting things. We shouldn't try to design systems to match that. Doesn't matter if it's a shit joke or not, it's not "wisdom" if it doesn't even stand on its own terms.
